"""DriverEmbeddingManager — Digital Twin Vector Engine.

Manages the full lifecycle of driver behavioral embeddings generated by the
21-D EmbeddingModel encoder. These embeddings are distinct from the MobileFaceNet
facial embeddings — they represent a driver's *behavioral* signature (driving
patterns, stress response, attention tendencies) rather than their face.

Responsibilities:
    - Generate 128-D session embeddings from feature matrix sequences.
    - Incrementally update embeddings as new sessions accumulate.
    - Perform cosine similarity and Euclidean distance comparisons.
    - Support KNN search across the driver corpus for cluster assignment.
    - Persist embeddings to/from the DriverEmbedding database table.
    - Compute embedding quality scores from calibration completeness.
    - Export embeddings to JSON and NumPy for analytics pipelines.

Embedding types in CogniDrive:
    - **Face embedding** (MobileFaceNet, 128-D/512-D) — who the driver is.
    - **Behavioral embedding** (EmbeddingModel, 128-D) — how the driver behaves.

Both are stored in the same ``DriverEmbedding`` table but serve different purposes.
This manager specifically handles behavioral embeddings.
"""

from __future__ import annotations

import json
import logging
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from sqlalchemy.orm import Session

from backend.ml.inference.embedding_model import EmbeddingModel, EmbeddingResult
from backend.database.models.embeddings import DriverEmbedding
from backend.database.models.driver_profile import DriverProfile

logger = logging.getLogger("CogniDrive.DriverEmbeddingManager")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EMBEDDING_DIM: int = 128
MIN_QUALITY_SAMPLES: int = 5     # Sessions needed for high-quality embedding
MAX_QUALITY_SAMPLES: int = 50    # Samples above this give diminishing returns
_COLD_START_WEIGHT: float = 0.3  # Weight for cold-start random-projection initialization


# ---------------------------------------------------------------------------
# Welford Online Statistics State
# ---------------------------------------------------------------------------


class WelfordState:
    """Numerically stable online mean and variance via Welford's algorithm.

    Supports vector/scalar states represented as NumPy arrays.
    """

    def __init__(self, mean: np.ndarray, m2: np.ndarray, count: int = 0) -> None:
        self.mean = np.array(mean, dtype=np.float64)
        self.m2 = np.array(m2, dtype=np.float64)
        self.count = count

    def update(self, val: np.ndarray) -> None:
        """Updates the running mean and sum of square deviations with a new sample."""
        val = np.array(val, dtype=np.float64)
        self.count += 1
        delta = val - self.mean
        self.mean += delta / self.count
        delta2 = val - self.mean
        self.m2 += delta * delta2

    @property
    def variance(self) -> np.ndarray:
        """Computes the sample variance."""
        if self.count < 2:
            return np.zeros_like(self.mean)
        return self.m2 / (self.count - 1)

    @property
    def std(self) -> np.ndarray:
        """Computes the sample standard deviation."""
        return np.sqrt(np.maximum(self.variance, 0.0))


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------



@dataclass
class EmbeddingSearchResult:
    """Result from a KNN search over the driver corpus.

    Attributes:
        driver_id: Primary key of the matched driver.
        similarity: Cosine similarity in [-1, 1].
        euclidean_distance: L2 distance between embeddings.
        rank: Position in sorted results (1 = closest).
    """
    driver_id: int
    similarity: float
    euclidean_distance: float
    rank: int = 1


# ---------------------------------------------------------------------------
# DriverEmbeddingManager
# ---------------------------------------------------------------------------


class DriverEmbeddingManager:
    """Manages behavioral embedding generation, updates, and retrieval.

    Thread-safe singleton. Uses the ``EmbeddingModel`` encoder to project
    21-D feature sequences into 128-D behavioral space.

    Attributes:
        _instance: Class-level singleton reference.
        _class_lock: Guards singleton creation.
        _encoder: Shared EmbeddingModel singleton.
    """

    _instance: Optional["DriverEmbeddingManager"] = None
    _class_lock: threading.Lock = threading.Lock()

    def __init__(self) -> None:
        """Initialises the manager and connects to the EmbeddingModel encoder."""
        self._encoder: EmbeddingModel = EmbeddingModel.get_instance()
        self._infer_lock: threading.Lock = threading.Lock()
        logger.info(
            "DriverEmbeddingManager: Initialized (encoder_fallback=%s).",
            self._encoder.is_fallback,
        )

    @classmethod
    def get_instance(cls) -> "DriverEmbeddingManager":
        """Returns the application-wide singleton instance.

        Returns:
            DriverEmbeddingManager: Shared singleton.
        """
        if cls._instance is None:
            with cls._class_lock:
                if cls._instance is None:
                    cls._instance = cls()
        return cls._instance

    # ------------------------------------------------------------------
    # Embedding generation
    # ------------------------------------------------------------------

    def generate_session_embedding(
        self, feature_matrix: np.ndarray
    ) -> EmbeddingResult:
        """Generates a single mean behavioral embedding from a session's feature matrix.

        Encodes every row of the ``(N, 21)`` feature matrix and returns the
        L2-normalized mean vector — a compact behavioral fingerprint for this session.

        Args:
            feature_matrix: ``(N, 21)`` float32 feature matrix from one session.
                N must be ≥ 1.

        Returns:
            EmbeddingResult: 128-D L2-normalized session embedding.

        Raises:
            ValueError: If feature_matrix has wrong shape or is empty.
        """
        if feature_matrix.ndim != 2 or feature_matrix.shape[1] != 21:
            raise ValueError(
                f"DriverEmbeddingManager.generate_session_embedding: "
                f"Expected (N, 21) matrix, got {feature_matrix.shape}."
            )
        if feature_matrix.shape[0] == 0:
            raise ValueError("Feature matrix must have at least one row.")

        with self._infer_lock:
            result = self._encoder.encode_mean_embedding(feature_matrix)

        logger.debug(
            "DriverEmbeddingManager: Session embedding generated "
            "(n_frames=%d, l2_norm=%.4f).",
            feature_matrix.shape[0],
            result.l2_norm,
        )
        return result

    def generate_embedding_from_vector(self, feature_vector: np.ndarray) -> EmbeddingResult:
        """Generates a behavioral embedding from a single 21-D feature vector.

        Args:
            feature_vector: 1-D float32 array of shape (21,).

        Returns:
            EmbeddingResult: 128-D embedding for this single frame.
        """
        with self._infer_lock:
            return self._encoder.encode(feature_vector)

    def cold_start_embedding(self, driver_id: int) -> np.ndarray:
        """Generates a deterministic cold-start embedding for a new driver.

        Used when no session data is available yet. Creates a reproducible
        128-D vector seeded from the driver_id. This places new drivers in a
        consistent region of the embedding space until real data accumulates.

        Args:
            driver_id: Primary key of the DriverProfile.

        Returns:
            np.ndarray: L2-normalized 128-D cold-start embedding, shape (128,).
        """
        rng = np.random.default_rng(seed=driver_id * 31337)
        raw = rng.standard_normal(EMBEDDING_DIM).astype(np.float32)
        norm = float(np.linalg.norm(raw))
        cold_emb = (raw / norm).astype(np.float32) if norm > 1e-8 else raw

        logger.info(
            "DriverEmbeddingManager.cold_start_embedding: Generated cold-start "
            "embedding for driver_id=%d.",
            driver_id,
        )
        return cold_emb

    # ------------------------------------------------------------------
    # Incremental updates
    # ------------------------------------------------------------------

    def incremental_update(
        self,
        old_embedding: np.ndarray,
        new_embedding: np.ndarray,
        old_count: int,
        momentum: float = 0.85,
    ) -> np.ndarray:
        """Updates the stored embedding using exponential moving average.

        Formula::

            updated = normalize(momentum * old + (1 - momentum) * new)

        An EMA update is preferred over simple averaging for behavioral embeddings
        because it gives more weight to the driver's stable long-term pattern
        while still adapting to behavioral drift.

        Args:
            old_embedding: Previous stored embedding, shape (128,).
            new_embedding: New session embedding, shape (128,).
            old_count: Number of sessions that contributed to old_embedding.
            momentum: EMA momentum factor.  Lower = faster adaptation.
                Auto-scales: high count → higher momentum (more stable).

        Returns:
            np.ndarray: Updated L2-normalized embedding, shape (128,).
        """
        # Scale momentum with sample count: few samples → faster learning
        effective_momentum = min(
            momentum, 1.0 - (1.0 / max(old_count + 1, 1))
        )
        effective_momentum = float(np.clip(effective_momentum, 0.0, 0.99))

        updated = (
            effective_momentum * old_embedding
            + (1.0 - effective_momentum) * new_embedding
        ).astype(np.float32)

        norm = float(np.linalg.norm(updated))
        if norm > 1e-8:
            updated = (updated / norm).astype(np.float32)

        logger.debug(
            "DriverEmbeddingManager.incremental_update: "
            "momentum=%.3f, count=%d.",
            effective_momentum,
            old_count,
        )
        return updated

    # ------------------------------------------------------------------
    # Similarity & distance
    # ------------------------------------------------------------------

    @staticmethod
    def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
        """Computes cosine similarity between two behavioral embeddings.

        Args:
            a: First embedding, shape (128,).
            b: Second embedding, shape (128,).

        Returns:
            float: Cosine similarity in [-1.0, 1.0].
        """
        a = np.asarray(a, dtype=np.float32).ravel()
        b = np.asarray(b, dtype=np.float32).ravel()
        norm_a = float(np.linalg.norm(a))
        norm_b = float(np.linalg.norm(b))
        if norm_a < 1e-8 or norm_b < 1e-8:
            return 0.0
        return float(np.clip(np.dot(a, b) / (norm_a * norm_b), -1.0, 1.0))

    @staticmethod
    def euclidean_distance(a: np.ndarray, b: np.ndarray) -> float:
        """Computes L2 (Euclidean) distance between two embeddings.

        Args:
            a: First embedding, shape (128,).
            b: Second embedding, shape (128,).

        Returns:
            float: L2 distance ≥ 0.0.
        """
        return float(np.linalg.norm(
            np.asarray(a, dtype=np.float32) - np.asarray(b, dtype=np.float32)
        ))

    # ------------------------------------------------------------------
    # KNN search
    # ------------------------------------------------------------------

    def knn_search(
        self,
        query_embedding: np.ndarray,
        corpus: List[Tuple[int, np.ndarray]],
        k: int = 5,
        metric: str = "cosine",
    ) -> List[EmbeddingSearchResult]:
        """Finds the K nearest behavioral neighbors in a driver corpus.

        Algorithm: Linear scan O(N × D). For a fleet of ≤ 1000 drivers this
        is fast enough on CPU without a vector index.

        Args:
            query_embedding: Query embedding, shape (128,).
            corpus: List of (driver_id, embedding) tuples.
            k: Number of nearest neighbors to return.
            metric: Distance metric — ``"cosine"`` (default) or ``"euclidean"``.

        Returns:
            List[EmbeddingSearchResult]: K results sorted by ascending distance
                (best match first).
        """
        if not corpus:
            return []

        q = np.asarray(query_embedding, dtype=np.float32).ravel()
        scored: List[Tuple[float, float, int]] = []

        for driver_id, emb in corpus:
            emb_arr = np.asarray(emb, dtype=np.float32).ravel()
            sim = self.cosine_similarity(q, emb_arr)
            dist = self.euclidean_distance(q, emb_arr)
            scored.append((sim, dist, driver_id))

        if metric == "cosine":
            scored.sort(key=lambda x: -x[0])  # descending similarity
        else:
            scored.sort(key=lambda x: x[1])   # ascending distance

        results = []
        for rank, (sim, dist, driver_id) in enumerate(scored[:k], start=1):
            results.append(
                EmbeddingSearchResult(
                    driver_id=driver_id,
                    similarity=round(sim, 6),
                    euclidean_distance=round(dist, 6),
                    rank=rank,
                )
            )
        return results

    # ------------------------------------------------------------------
    # Cluster assignment
    # ------------------------------------------------------------------

    def assign_cluster(
        self,
        embedding: np.ndarray,
        cluster_centroids: np.ndarray,
    ) -> Tuple[int, float]:
        """Assigns an embedding to the nearest cluster centroid.

        Args:
            embedding: Driver behavioral embedding, shape (128,).
            cluster_centroids: Array of centroid vectors, shape (K, 128).

        Returns:
            Tuple[int, float]: (cluster_index, cosine_similarity_to_centroid).
        """
        emb = np.asarray(embedding, dtype=np.float32).ravel()
        similarities = np.array([
            self.cosine_similarity(emb, centroids)
            for centroids in cluster_centroids
        ])
        best_idx = int(np.argmax(similarities))
        return best_idx, float(similarities[best_idx])

    # ------------------------------------------------------------------
    # Quality scoring
    # ------------------------------------------------------------------

    @staticmethod
    def compute_quality_score(
        calibration_samples: int,
        session_diversity: float = 0.5,
        embedding_stability: float = 0.5,
    ) -> float:
        """Computes the embedding quality score from calibration metadata.

        Formula::

            quality = 0.40 * completeness + 0.30 * diversity + 0.30 * stability

        Where ``completeness`` is derived from the number of samples relative
        to ``MAX_QUALITY_SAMPLES``.

        Args:
            calibration_samples: Number of sessions embedded so far.
            session_diversity: Estimated diversity of driving conditions [0, 1].
            embedding_stability: Embedding update stability metric [0, 1].

        Returns:
            float: Quality score in [0.0, 1.0].
        """
        completeness = min(
            float(calibration_samples) / MAX_QUALITY_SAMPLES, 1.0
        )
        quality = (
            0.40 * completeness
            + 0.30 * float(np.clip(session_diversity, 0.0, 1.0))
            + 0.30 * float(np.clip(embedding_stability, 0.0, 1.0))
        )
        return float(np.clip(quality, 0.0, 1.0))

    # ------------------------------------------------------------------
    # Persistence helpers
    # ------------------------------------------------------------------

    def load_from_db(
        self, driver_id: int, db: Session
    ) -> Optional[np.ndarray]:
        """Loads a driver's behavioral embedding from the database.

        Args:
            driver_id: Primary key of the DriverProfile.
            db: Active SQLAlchemy session.

        Returns:
            Optional[np.ndarray]: Embedding vector of shape (128,), or None.
        """
        record = (
            db.query(DriverEmbedding)
            .filter(DriverEmbedding.driver_id == driver_id)
            .first()
        )
        if record is None:
            return None
        return record.to_numpy()

    def save_to_db(
        self,
        driver_id: int,
        embedding: np.ndarray,
        db: Session,
        quality_score: float = 0.0,
        calibration_samples: int = 0,
    ) -> DriverEmbedding:
        """Persists or updates a driver's behavioral embedding in the database.

        Creates a new DriverEmbedding record if none exists, or updates the
        existing one using ``update_embedding()``.

        Args:
            driver_id: Primary key of the DriverProfile.
            embedding: L2-normalized behavioral embedding, shape (128,).
            db: Active SQLAlchemy session (caller must commit).
            quality_score: Embedding quality in [0.0, 1.0].
            calibration_samples: Total session count.

        Returns:
            DriverEmbedding: The created or updated record (not yet committed).
        """
        record = (
            db.query(DriverEmbedding)
            .filter(DriverEmbedding.driver_id == driver_id)
            .first()
        )
        if record is None:
            record = DriverEmbedding(driver_id=driver_id)
            db.add(record)

        record.from_numpy(embedding)
        record.embedding_quality_score = float(np.clip(quality_score, 0.0, 1.0))
        record.calibration_samples = calibration_samples
        record.last_updated = datetime.now(timezone.utc)
        record.version = record.version + 1 if record.version else 1

        logger.info(
            "DriverEmbeddingManager.save_to_db: Saved embedding for driver_id=%d "
            "(dim=%d, quality=%.3f, samples=%d).",
            driver_id,
            len(embedding),
            quality_score,
            calibration_samples,
        )
        return record

    # ------------------------------------------------------------------
    # Export utilities
    # ------------------------------------------------------------------

    @staticmethod
    def to_json(embedding: np.ndarray, driver_id: int, metadata: Optional[Dict[str, Any]] = None) -> str:
        """Exports an embedding to a JSON string.

        Args:
            embedding: Embedding vector, shape (128,).
            driver_id: Owning driver's primary key.
            metadata: Optional additional metadata dict.

        Returns:
            str: JSON string representation.
        """
        payload: Dict[str, Any] = {
            "driver_id": driver_id,
            "embedding_dimension": len(embedding),
            "embedding_vector": embedding.tolist(),
            "exported_at": datetime.now(timezone.utc).isoformat(),
        }
        if metadata:
            payload.update(metadata)
        return json.dumps(payload, indent=2)

    @staticmethod
    def from_json(json_str: str) -> Tuple[int, np.ndarray]:
        """Imports an embedding from a JSON string.

        Args:
            json_str: JSON string produced by ``to_json()``.

        Returns:
            Tuple[int, np.ndarray]: (driver_id, embedding_vector).

        Raises:
            ValueError: If the JSON is malformed or missing required keys.
        """
        try:
            data = json.loads(json_str)
            driver_id = int(data["driver_id"])
            vector = np.array(data["embedding_vector"], dtype=np.float32)
            return driver_id, vector
        except (KeyError, TypeError, json.JSONDecodeError) as exc:
            raise ValueError(f"DriverEmbeddingManager.from_json: Invalid JSON: {exc}") from exc

    @staticmethod
    def to_numpy_matrix(
        embeddings: List[Tuple[int, np.ndarray]]
    ) -> Tuple[List[int], np.ndarray]:
        """Stacks a list of (driver_id, embedding) tuples into a matrix.

        Args:
            embeddings: List of (driver_id, embedding) tuples.

        Returns:
            Tuple[List[int], np.ndarray]: (driver_ids, matrix of shape (N, 128)).
        """
        driver_ids = [d for d, _ in embeddings]
        matrix = np.stack([e for _, e in embeddings], axis=0).astype(np.float32)
        return driver_ids, matrix
